#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-excon
Version  : 0.45.4
Release  : 1
URL      : https://rubygems.org/downloads/excon-0.45.4.gem
Source0  : https://rubygems.org/downloads/excon-0.45.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-bundler
BuildRequires : rubygem-delorean
BuildRequires : rubygem-eventmachine
BuildRequires : rubygem-json
BuildRequires : rubygem-open4
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-shindo
BuildRequires : rubygem-sinatra

%description
# excon
Usable, fast, simple Ruby HTTP 1.1
Excon was designed to be simple, fast and performant. It works great as a general HTTP(s) client and is particularly well suited to usage in API clients.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n excon-0.45.4
gem spec %{SOURCE0} -l --ruby > rubygem-excon.gemspec

%build
gem build rubygem-excon.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
excon-0.45.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/excon-0.45.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/cdesc-Connection.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/connection%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/detect_content_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/error_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/params%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/proxy%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/requests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/retry_limit%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/retry_limit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/setup_proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/sockets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Connection/validate_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Accepted/cdesc-Accepted.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/BadGateway/cdesc-BadGateway.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/BadRequest/cdesc-BadRequest.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ClientError/cdesc-ClientError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Conflict/cdesc-Conflict.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Continue/cdesc-Continue.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Created/cdesc-Created.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ExpectationFailed/cdesc-ExpectationFailed.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Forbidden/cdesc-Forbidden.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Found/cdesc-Found.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/GatewayTimeout/cdesc-GatewayTimeout.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Gone/cdesc-Gone.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/HTTPStatusError/cdesc-HTTPStatusError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/HTTPStatusError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/HTTPStatusError/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/HTTPStatusError/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Informational/cdesc-Informational.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/InternalServerError/cdesc-InternalServerError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/InvalidStub/cdesc-InvalidStub.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/LengthRequired/cdesc-LengthRequired.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/MethodNotAllowed/cdesc-MethodNotAllowed.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/MovedPermanently/cdesc-MovedPermanently.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/MultipleChoices/cdesc-MultipleChoices.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NoContent/cdesc-NoContent.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NonAuthoritativeInformation/cdesc-NonAuthoritativeInformation.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NotAcceptable/cdesc-NotAcceptable.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NotFound/cdesc-NotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NotImplemented/cdesc-NotImplemented.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/NotModified/cdesc-NotModified.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/OK/cdesc-OK.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/PartialContent/cdesc-PartialContent.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/PaymentRequired/cdesc-PaymentRequired.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/PreconditionFailed/cdesc-PreconditionFailed.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ProxyAuthenticationRequired/cdesc-ProxyAuthenticationRequired.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ProxyConnectionError/cdesc-ProxyConnectionError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ProxyParseError/cdesc-ProxyParseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Redirection/cdesc-Redirection.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/RequestEntityTooLarge/cdesc-RequestEntityTooLarge.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/RequestTimeout/cdesc-RequestTimeout.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/RequestURITooLong/cdesc-RequestURITooLong.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/RequestedRangeNotSatisfiable/cdesc-RequestedRangeNotSatisfiable.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ResetContent/cdesc-ResetContent.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ResponseParseError/cdesc-ResponseParseError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/SeeOther/cdesc-SeeOther.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ServerError/cdesc-ServerError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/ServiceUnavailable/cdesc-ServiceUnavailable.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/SocketError/cdesc-SocketError.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/SocketError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/SocketError/socket_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/StubNotFound/cdesc-StubNotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Success/cdesc-Success.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/SwitchingProtocols/cdesc-SwitchingProtocols.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/TemporaryRedirect/cdesc-TemporaryRedirect.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Timeout/cdesc-Timeout.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/TooManyRequests/cdesc-TooManyRequests.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/Unauthorized/cdesc-Unauthorized.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/UnprocessableEntity/cdesc-UnprocessableEntity.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/UnsupportedMediaType/cdesc-UnsupportedMediaType.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/UseProxy/cdesc-UseProxy.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Errors/status_error-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/assoc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/cdesc-Headers.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_fetch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_has_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_merge%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_reader-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_rehash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/raw_writer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/rehash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Headers/values_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Base/error_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Base/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Base/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Decompress/cdesc-Decompress.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Decompress/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Decompress/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/EscapePath/cdesc-EscapePath.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/EscapePath/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Expects/cdesc-Expects.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Expects/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Idempotent/cdesc-Idempotent.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Idempotent/error_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Instrumentor/cdesc-Instrumentor.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Instrumentor/error_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Instrumentor/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Instrumentor/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Mock/cdesc-Mock.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/Mock/request_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/RedirectFollower/cdesc-RedirectFollower.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/RedirectFollower/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/ResponseParser/cdesc-ResponseParser.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/ResponseParser/response_call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Middleware/cdesc-Middleware.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/PrettyPrinter/cdesc-PrettyPrinter.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/PrettyPrinter/pp-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/body%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/cdesc-Response.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/get_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/headers%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/local_address-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/local_port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/parse_headers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/pp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/reason_phrase%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/reason_phrase-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/remote_ip%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/remote_ip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/status%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/status_line%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Response/status_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/SSLSocket/cdesc-SSLSocket.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/SSLSocket/connect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/SSLSocket/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/cdesc-Socket.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/connect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/data-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/legacy_readline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/local_address-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/local_port-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/params%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/raise_timeout_error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/read_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/read_nonblock-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/readline-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/remote_ip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/timeout_reached-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/unpacked_sockaddr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/write-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/write_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Socket/write_nonblock-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/StandardInstrumentor/cdesc-StandardInstrumentor.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/StandardInstrumentor/instrument-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/UnixSocket/cdesc-UnixSocket.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/UnixSocket/connect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/cdesc-Utils.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/connection_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/escape_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/port_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/query_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/request_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/split_header_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/unescape_form-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/Utils/unescape_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/cdesc-Excon.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/defaults%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/defaults-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/display_warning-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/mock%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/mock-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/ssl_ca_path%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/ssl_ca_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/ssl_verify_peer%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/ssl_verify_peer-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/stub-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/stub_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/stubs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/Excon/unstub-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/IO/WaitReadable/cdesc-WaitReadable.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/IO/WaitWritable/cdesc-WaitWritable.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/IO/cdesc-IO.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/URI/Generic/cdesc-Generic.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/URI/Generic/hostname-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/URI/cdesc-URI.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/excon-0.45.4/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/CONTRIBUTORS.md
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/Gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/README.md
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/class_vs_lambda.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/concat_vs_insert.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/concat_vs_interpolate.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/cr_lf.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/downcase-eq-eq_vs_casecmp.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/excon.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/excon_vs.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/for_vs_array_each.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/for_vs_hash_each.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/has_key-vs-lookup.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/headers_case_sensitivity.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/headers_split_vs_match.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/implicit_block-vs-explicit_block.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/merging.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/single_vs_double_quotes.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/string_ranged_index.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/strip_newline.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/benchmarks/vs_stdlib.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/changelog.txt
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/data/cacert.pem
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/excon.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/connection.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/constants.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/extensions/uri.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/headers.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/decompress.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/escape_path.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/expects.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/idempotent.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/mock.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/redirect_follower.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/pretty_printer.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/socket.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/ssl_socket.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/standard_instrumentor.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/unix_socket.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/lib/excon/utils.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/authorization_header_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/bad_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/basic_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/complete_responses.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/data/127.0.0.1.cert.crt
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/data/127.0.0.1.cert.key
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/data/excon.cert.crt
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/data/excon.cert.key
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/data/xs
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/errors_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/header_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/canned_response_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/decompress_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/escape_path_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/idempotent_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/instrumentation_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/mock_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/middlewares/redirect_follower_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/pipeline_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/proxy_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/query_string_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/basic.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/basic_auth.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/deflater.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/proxy.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/query_string.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/redirecting.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/request_headers.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/request_methods.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/response_header.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/ssl.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/ssl_mismatched_cn.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/ssl_verify_peer.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/streaming.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/thread_safety.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/timeout.ru
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/rackups/webrick_patch.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/request_headers_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/request_method_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/request_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/response_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/servers/bad.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/servers/eof.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/servers/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/servers/good.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/thread_safety_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/timeout_tests.rb
/usr/lib64/ruby/gems/2.2.0/gems/excon-0.45.4/tests/utils_tests.rb
/usr/lib64/ruby/gems/2.2.0/specifications/excon-0.45.4.gemspec
